apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: docker-desktop
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ''
    node.kubernetes.io/exclude-from-external-load-balancers: ''
    color: grey
  name: grey
