apiVersion: v1
kind: Pod
metadata:
  labels:
    name: simple-webapp
    pod-template-hash: 7b4d799f4d
  name: simple-webapp-deployment-7b4d799f4d-6rsgn
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: simple-webapp-deployment-7b4d799f4d
spec:
  containers:
    - image: kodekloud/simple-webapp:red
      name: simple-webapp
      ports:
        - containerPort: 8080
          protocol: TCP
