apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-08-09T10:20:29Z'
  name: webapp-service
  namespace: default
  resourceVersion: '898'
  uid: 63436ec4-0876-43aa-81d5-7720b91dea5f
spec:
  clusterIP: 10.43.198.146
  clusterIPs:
    - 10.43.198.146
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: simple-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
